#  _           _          ____                       _              _            __ ___
# | |         | |        |  _ \            /\       | |            | |          /_ |__ \
# | |     ___ | |_ ___   | |_) |_   _     /  \   ___| |__   ___  __| | ___  _ __ | |  ) |
# | |    / _ \| __/ _ \  |  _ <| | | |   / /\ \ / __| '_ \ / _ \/ _` |/ _ \| '_ \| | / /
# | |___| (_) | || (_) | | |_) | |_| |  / ____ \ (__| | | |  __/ (_| | (_) | | | | |/ /_
# |______\___/ \__\___/  |____/ \__, | /_/    \_\___|_| |_|\___|\__,_|\___/|_| |_|_|____|
#                                __/ |
#                               |___/

# /!\ Timer value is in seconds
# /!\ Default profit is the amount when a new loto is started
loto:
  default-profit: 1000
  max-deposit: 5000
  timer: 600
  prefix: "§b[§cLoto§b]"